# Generated by Django 5.2.7 on 2025-12-25 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_category_delete_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Transaction date')),
                ('description', models.CharField(help_text='Transaction description from bank', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive or negative)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes or memo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Category assigned by AI or user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pages.category')),
                ('user', models.ForeignKey(help_text='Owner of this transaction', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
