# Generated by Django 5.2.7 on 2026-05-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_defaultcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ai_confidence',
            field=models.FloatField(blank=True, help_text='AI classification confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_ai_categorized',
            field=models.BooleanField(default=False, help_text='True if category was assigned by the AI engine'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant_name',
            field=models.CharField(blank=True, help_text='Merchant or payee name (e.g. Carrefour, Uber, K-Electric)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, help_text='Transaction type (e.g. POS Swipe, Bill Payment, Wallet Transfer)', max_length=50, null=True),
        ),
    ]
