# Generated by Django 5.2.7 on 2026-05-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_transaction_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ai_suggested_category',
            field=models.CharField(blank=True, help_text='Category suggested by AI when it falls into Uncategorized', max_length=50, null=True),
        ),
    ]
