# Generated by Django 6.0 on 2026-06-08 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_transaction_ai_suggested_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Uploaded Files',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, help_text='File from which this transaction was imported', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pages.uploadedfile'),
        ),
    ]
