# Generated by Django 5.2.7 on 2026-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_uploadedfile_transaction_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Extracted unique transaction reference ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of core fields to detect duplicates', max_length=64, null=True),
        ),
    ]
