# Generated by Django 5.2.7 on 2026-06-27 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_gemini_model'),
        ('pages', '0008_transaction_transaction_id_transaction_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ai_run',
            field=models.ForeignKey(blank=True, help_text='Link to the telemetry log representing the API call that categorized this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.aitelemetrylog'),
        ),
    ]
