# Generated by Django 5.2.7 on 2026-06-24 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_provider', models.CharField(choices=[('gemini', 'Google Gemini AI'), ('openai', 'OpenAI')], default='gemini', max_length=20)),
                ('gemini_model', models.CharField(default='gemini-2.0-flash', max_length=50)),
                ('openai_model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
