# Generated by Django 5.2.7 on 2026-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deepseek_model',
            field=models.CharField(default='deepseek-chat', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini AI'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek AI')], default='gemini', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='openai_model',
            field=models.CharField(default='gpt-4.1-nano', max_length=50),
        ),
    ]
