# Generated by Django 5.2.7 on 2026-06-26 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_deepseek_api_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
        migrations.CreateModel(
            name='AITelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('batch_size', models.IntegerField()),
                ('latency_seconds', models.FloatField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('calculated_cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('avg_confidence', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_telemetry_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Telemetry Log',
                'verbose_name_plural': 'AI Telemetry Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
