# Generated by Django 5.2.7 on 2026-06-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_gemini_model_aitelemetrylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gemini_model',
            field=models.CharField(default='gemini-3.1-flash-lite', max_length=50),
        ),
    ]
